version: '3.1'
services:
  db:
    platform: linux/x86_64
    image: mysql
    restart: always
    command: mysqld --log-error=/var/log/mysql/error.log --log-error-verbosity=3 --general-log=1 --general-log-file=/var/log/mysql/general-log.log
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
    volumes:
      - ./school.sql:/school.sql
      - ./timestamps.sql:/timestamps.sql
      - ./mysql.log:/var/log/mysql/general-log.log
      - ./error.log:/var/log/mysql/error.log