version: '3.1'
services:
  db:
    platform: linux/x86_64
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
    volumes:
      - ./school.sql:/school.sql
      - ./timestamps.sql:/timestamps.sql